
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'SBLSBRkeyIdIdValueidNombrevalueNombreidEmailvalueEmailidTelefonovalueTelefonotextIdValue SBL SBR idEmail idNombre idTelefono keyId text valueEmail valueNombre valueTelefonoS : SBL A A : keyId BB : SBR CC : '
    
_lr_action_items = {'SBL':([0,],[2,]),'$end':([1,3,5,6,7,],[0,-1,-2,-4,-3,]),'keyId':([2,],[4,]),'SBR':([4,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'A':([2,],[3,]),'B':([4,],[5,]),'C':([6,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> SBL A','S',2,'p_start','html_yacc.py',26),
  ('A -> keyId B','A',2,'p_keyId','html_yacc.py',31),
  ('B -> SBR C','B',2,'p_SBR','html_yacc.py',37),
  ('C -> <empty>','C',0,'p_end','html_yacc.py',42),
]
