
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'SBLSBRkeyIdidValueidNombrevalueNombreidEmailvalueEmailidTelefonovalueTelefonotextSBL SBR idEmail idNombre idTelefono idValue keyId text valueEmail valueNombre valueTelefonoS : SBL A SBRA : B keyId idValue B idNombre valueNombre B idEmail valueEmail B idTelefono valueTelefono B AA : B keyId idValue B idNombre valueNombre B idEmail valueEmail B idTelefono valueTelefono BB : text BB : textB : '
    
_lr_action_items = {'SBL':([0,],[2,]),'$end':([1,6,],[0,-1,]),'text':([2,5,8,9,12,15,18,19,],[5,5,-4,5,5,5,5,5,]),'keyId':([2,4,5,8,18,19,],[-6,7,-5,-4,-6,-6,]),'SBR':([3,5,8,18,19,20,],[6,-5,-4,-6,-3,-2,]),'idNombre':([5,8,9,10,],[-5,-4,-6,11,]),'idEmail':([5,8,12,13,],[-5,-4,-6,14,]),'idTelefono':([5,8,15,16,],[-5,-4,-6,17,]),'idValue':([7,],[9,]),'valueNombre':([11,],[12,]),'valueEmail':([14,],[15,]),'valueTelefono':([17,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'A':([2,19,],[3,20,]),'B':([2,5,9,12,15,18,19,],[4,8,10,13,16,19,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> SBL A SBR','S',3,'p_start','html_yacc.py',48),
  ('A -> B keyId idValue B idNombre valueNombre B idEmail valueEmail B idTelefono valueTelefono B A','A',14,'p_nodeA_A','html_yacc.py',52),
  ('A -> B keyId idValue B idNombre valueNombre B idEmail valueEmail B idTelefono valueTelefono B','A',13,'p_nodeA_B','html_yacc.py',56),
  ('B -> text B','B',2,'p_nodeB_B','html_yacc.py',60),
  ('B -> text','B',1,'p_nodeB','html_yacc.py',64),
  ('B -> <empty>','B',0,'p_end','html_yacc.py',68),
]
